"""empty message

Revision ID: fa1c91c6343d
Revises: 2a010af10ae2
Create Date: 2022-08-10 17:37:41.279961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa1c91c6343d'
down_revision = '2a010af10ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website', sa.String(), nullable=True))
    op.drop_column('Venue', 'website_link')
    op.alter_column('shows', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('shows', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('shows', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('Venue', sa.Column('website_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'website')
    # ### end Alembic commands ###
